### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by pinbeu** [yasoob/nrc-exporter#14]
Hi Yasoob,

I ran nrc-exporter with a token, it successfully got all my 64 running activities from 3 pages.
Then it started getting activity details for each one of them, it also worked.
Then it started parsing them. A few of them didn't contain lat/lon information but the program kept running until activity #58, and the 59th rose a Traceback error :

> Traceback (most recent call last):
  File "c:\users\pinbeu\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\pinbeu\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\pinbeu\AppData\Local\Programs\Python\Python38-32\Scripts\nrc-exporter.exe\__main__.py", line 7, in <module>
  File "c:\users\pinbeu\appdata\local\programs\python\python38-32\lib\site-packages\nrc_exporter.py", line 631, in main
    parsed_data = parse_activity_data(json_data)
  File "c:\users\pinbeu\appdata\local\programs\python\python38-32\lib\site-packages\nrc_exporter.py", line 449, in parse_activity_data
    for i, metric in enumerate(activity["metrics"]):
KeyError: 'metrics'

In case you're still working on this project, I'd be happy to hear from you about this error :)

Thanks for your great script and have a nice day,
Cheers,
pinbeu

**Comment by yihong0618** [comment]
@pinbeu 
Its because this run does not contain gpx data, maybe it is probably treadmill running.
I can fix it later.

**Comment by yihong0618** [comment]
@pinbeu 
Hi~
I have fixed this bug in https://github.com/yasoob/nrc-exporter/commit/b6951b288f4a48bc4e93bb7ba7a63ed2f4ed06b0

But it is still not uploaded to pypi.
You can follow these steps:
1. uninstall `nrc-exporter`  -- pip uninstall nrc-exporter
2. clone this repo
3. python nrc_exporter.py --help use local command

**Comment by pinbeu** [comment]
Thanks for your swift reply, it's now working, thanks !

**Comment by yihong0618** [comment]
@pinbeu My pleasure.
