### ISSUE TITLE
A failure on one of the data files

### ISSUE THREAD

**Issue by jonnyzzz** [yasoob/nrc-exporter#20]
Traceback (most recent call last):
  File "/opt/homebrew/bin/nrc-exporter", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/nrc_exporter.py", line 631, in main
    parsed_data = parse_activity_data(json_data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/nrc_exporter.py", line 449, in parse_activity_data
    for i, metric in enumerate(activity["metrics"]):
                               ~~~~~~~~^^^^^^^^^^^
KeyError: 'metrics'

Do we have error handling so it can skip the problematic file and move on to the next one? 
The error does not log which file was the problematic

**Comment by jonnyzzz** [comment]
In my case it was only able to process 1/3 of the data 
<img width="305" alt="image" src="https://github.com/yasoob/nrc-exporter/assets/256431/7070b2ac-9ffd-4e00-80f7-dd9d6d64f329">
